language: php

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=1.30.0; SMW=2.5.6
      php: 5.6

install:
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-result-formats.sh

script:
  - bash ./build/travis/run-tests.sh

cache:
  directories:
    - $HOME/.composer/cache
